version: '3.8'

services:
  bramify:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"  # For OAuth callback
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USER_IDS=${TELEGRAM_ALLOWED_USER_IDS}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_SHEETS_SPREADSHEET_ID=${GOOGLE_SHEETS_SPREADSHEET_ID}
      - GOOGLE_SHEETS_CREDENTIALS_FILE=config/credentials.json